apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gol
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gol
    spec:
      containers:
      - name: gameoflife
        image: veerendradevops/openmrs:2.1.2
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name:  gameoflife
spec:
  selector:
    app:  gol
  type:  NodePort
  ports:
  - name:  http
    port:  8080
    nodePort: 30001
    protocol: TCP